### ISSUE TITLE
Issue using the Benchmark

### ISSUE THREAD

**Issue by valerymolinalika** [JonasLamy/LiverVesselness#8]
Hi, I am currently facing problems with using the benchmark to segment perivascular spaces (PVS) in MRI, at the moment I am trying to use the Antiga filter for this task.

I have followed the steps in the guide, defining the settingFile as follows: 

`{
    "Settings":
    {
	"name":"newBenchark",
	"path":"/home/valery/Tesis/pruebas",
	"inputVolumesList":"fileLists/prueba1.txt",
	"algorithmSets":"paramSets/Frangi.json",
	"maskList":["Organ"],
	"enhancementMask":"Organ",
	"nbThresholds":10,
	"removeResultsVolumes":false,
	"rescaleFilters":false 
    }
}
`
the inputVolumesList:

`AAA417 // ID of the first sequence 
/home/valery/Tesis/Images/AAA417/AAA417_56_hm_tse_ac-pc_512_p2_reg2ref_Warped.nii.gz // input data
/home/valery/Tesis/Images/AAA417/AAA417_56_hm_tse_ac-pc_512_p2_PVS_reg2ref_Warped.nii.gz // groundtruth
/home/valery/Tesis/Images/AAA417/dummy_mask.nii // 1rst mask`

and the algorithmSets: for this use one of those defined in the repository. 

However, at the moment of running the benchmark I encounter this problem: 

![imagen_2024-03-17_160710938](https://github.com/JonasLamy/LiverVesselness/assets/62066912/d8716ea6-b259-4921-bcdf-794f833263f3)

I seek guidance to identify the underlying causes of these inconsistencies. Could there be overlooked steps or parameters contributing to this issue? Any assistance in resolving these sporadic errors would be greatly appreciated.

Thank you

**Comment by JonasLamy** [comment]
Hi,

The program seems to fail at the second step of the directory creation...

At the beginning, the benchmark is supposed to create 3 directories.
- one directory using the last part of the path, in your case a "pruebas" directory at location /home/valery/Tesis
-  one directory with the name of the benchmark, in your case "newBenchmark". The path for this one is created as path + "/" + name and should be "/home/valery/Tesis/pruebas/newBenchmark" and not "/home/valery/Tesis/pruebas/" alone...

I don't know why it doesn't displays the full path, but could you check the following things : 
- pruebas directory was created successfully 
- You have directory creation rights in this folder
- Try one of the reproductibility parameter file with the ircad dataset for instance.

Alternatively, you can try to create the directory tree yourself using mkdir : 
/home/valery/Tesis/pruebas
                                         |_newBenchmark
                                                                 |_ csv

Keep me updated on your progress.

**Comment by valerymolinalika** [comment]
Thank you for your suggestions. Unfortunately, even after trying those solutions and ensuring that the prerequisites were met, the program still doesn't seem to work as expected.

Given the issue persists, it might be beneficial for us to define the step-by-step process for the benchmark creation. This way, we can ensure that we're not missing any crucial steps along the way.

Could you please provide detailed instructions or clarify any specific steps we should take to set up the benchmark correctly? Your guidance would be greatly appreciated.

**Comment by JonasLamy** [comment]
Hello,

Could you elaborate on what didn't work ? Is it failing at the same step as before ? What directory tree did it create ?

There is a whole README.md that describes the necessary step to set up a benchmark. But here the issue was related to writing directory on your system...which is strange, as I've tested creation on both linux and mac os before.

I'll see wether I can set up an Hello World configuration for trouble shooting.

**Comment by JonasLamy** [comment]
Hello,

A quick question. What is your OS version ? Mine was ubuntu bionic beever 18.04 LTS. I have not tested the directory creation with newer versions. It might be the cause.

**Comment by valerymolinalika** [comment]
Hello,

Indeed, I believe the issue was due to the OS version. We tested the version you mentioned, and it worked correctly. Thank you very much for your assistance.
